### ISSUE TITLE
Swedish transliteration

### ISSUE THREAD

**Issue by tobiassjosten** [cocur/slugify#80] opened 2015-10-10 13:02 UTC
Hi! When we transliterate the Swedish characters å, ä and ö, we use a, a and o. I see you're using the German system of aa, ae and oe for Slugify.

Not really sure how best to solve this but I thought I'd raise the issue.

**Comment by tobiassjosten** [comment] 2015-10-10 13:02
Found a discussion on the subject that could be interesting: http://forum.camendesign.com/language_specific_transliteration_re_transliteration

**Comment by tobiassjosten** [comment] 2015-10-10 13:02
Found a discussion on the subject that could be interesting: http://forum.camendesign.com/language_specific_transliteration_re_transliteration

**Comment by florianeckerstorfer** [comment] 2015-10-10 17:06
This is related to #56, currently the when there are conflicts we use the one of the most popular language as the default transliteration.

In the current implementation there is no easy fix for this, however, this is something I want to solve for 2.0

**Comment by tobiassjosten** [comment] 2015-10-11 12:24
Couldn't the `slugify()` method be made to take a second, optional parameter for locale of the source string? That'd be BC and make some kind of sense, since you probably know the language of the original text.

Or what do you have planned for 2.0?

Let me know if I can help!

**Comment by florianeckerstorfer** [comment] 2015-10-11 12:39
Please read the discussion in #56. The problem is not the code, but how to organize the data.

Yes, we plan to provide a solution to this problem in 2.0

**Comment by florianeckerstorfer** [comment] 2015-10-11 12:50
I want to keep this ticket open, I don't want to forget about Swedish

**Comment by florianeckerstorfer** [comment] 2015-11-07 10:40
I think this can be closed because of #81

**Closed by florianeckerstorfer** 2015-11-07 10:40 UTC
