### ISSUE TITLE
Empty regexp error when using option "lowercase" to false

### ISSUE THREAD

**Issue by adadgio** [cocur/slugify#99] opened 2016-02-23 17:30 UTC
When specifiying the lowercase option

```
$slugify = new Slugify(array('lowercase' => false)); // keep uppercase letters
$this->name = $slugify->slugify("Annonce: Jean Claude vends dame", '_');
```

An error is thrown:

`Warning: preg_replace(): Empty regular expression`

Specifying a regexp as second option does not fix the issue either.

**Comment by florianeckerstorfer** [comment] 2016-02-23 21:19
Which version or branch are you using? Because there is a test and it passes for the `master` branch.

**Comment by adadgio** [comment] 2016-02-24 07:28
I'm using release 1.4. It doesn't pass unit tests according the git... ;-)

**Comment by florianeckerstorfer** [comment] 2016-02-24 20:12
According to Travis the 1.4 branch does work. (see https://travis-ci.org/cocur/slugify/builds/111551117)

I also tested it out on my machine and I can't reproduce the error. Which PHP version are you using?

**Comment by adadgio** [comment] 2016-02-25 07:58
PHP 5.6.16

**Comment by florianeckerstorfer** [comment] 2016-02-26 07:19
The AppVeyor tests failed. In this case AppVeyor failed because the setup of PHP on the windows machine didn't work.

**Comment by florianeckerstorfer** [comment] 2016-03-17 16:10
I am closing this, if the problem persists please reopen.

**Closed by florianeckerstorfer** 2016-03-17 16:10 UTC
